# Generated by Django 3.1.8 on 2021-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('type_contact', models.CharField(max_length=255, verbose_name='Type')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modification')),
                ('contact_document_pdf', models.FileField(blank=True, null=True, upload_to='rdv_pp_document')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
